### 실손보험에서 급여 본인부담금에 대한 보험사의 보험금 지출 차이 예측

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/Users/jieunpark/문서/25_2_EDA/merged_preprocessed_with_22.csv", encoding='euc-kr', index_col=0)
df

,연령,298 질병분류,22대 질병분류,진료형태,진료실인원수,입내원일수,요양급여일수,진료비,급여비,진료실인원수(급여),급여건수(급여),입내원일수(급여),요양일수(급여),총진료비(급여),기금부담금(급여)
0,0,001,1,계,0.0,0.0,2.400000e+01,9.100000e+01,75,0,0,0,0,0,0
1,0,001,1,입원,0.0,0.0,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0
2,0,001,1,외래,0.0,0.0,2.400000e+01,9.100000e+01,75,0,0,0,0,0,0
3,0,002,1,계,0.0,0.0,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0
4,0,002,1,입원,0.0,0.0,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16195,계,계,계,입원,7317434.0,131337135.0,2.128787e+08,3.805222e+10,30900118990,480949,2517165,41841183,49114639,5798762786190,5588981626730
16196,계,계,계,외래,48583891.0,856955468.0,1.126234e+10,6.922396e+10,49550793129,1535891,50405429,49245884,134120504,3258606442500,3177187816970
16197,계,기타,기타,계,8118595.0,13964789.0,1.343919e+08,1.400535e+09,1138466883,279227,622804,971559,1985658,122387452640,119985647660
16198,계,기타,기타,입원,260605.0,2107202.0,3.054570e+06,6.000271e+08,511067206,38349,60090,411165,506618,100564770320,98756727650
16199,계,기타,기타,외래,7945418.0,11857587.0,1.313373e+08,8.005077e+08,627399676,240767,395612,393292,430190,17723233470,17196208620

In [ ]:
df['연령'].unique(), df['298 질병분류'].unique()

(array(['0', '1-4', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
        '40-44', '45-49', '5-9', '50-54', '55-59', '60-64', '65-69',
        '70-74', '75-', '계'], dtype=object),
 array(['001', '002', '003', '004', '005', '006', '007', '008', '009',
        '010', '011', '012', '013', '014', '015', '016', '017', '018',
        '019', '020', '021', '022', '023', '024', '025', '026', '027',
        '028', '029', '030', '031', '032', '033', '034', '035', '036',
        '037', '038', '039', '040', '041', '042', '043', '044', '045',
        '046', '047', '048', '049', '050', '051', '052', '053', '054',
        '055', '056', '057', '058', '059', '060', '061', '062', '063',
        '064', '065', '066', '067', '068', '069', '070', '071', '072',
        '073', '074', '075', '076', '077', '078', '079', '080', '081',
        '082', '083', '084', '085', '086', '087', '088', '089', '090',
        '091', '092', '093', '094', '095', '096', '097', '098', '099',
        '100', '101', '102', '103', '104', '105', '106', '107', '108',
        '109', '110', '111', '112', '113', '114', '115', '116', '117',
        '118', '119', '120', '121', '122', '123', '124', '125', '126',
        '127', '128', '129', '130', '131', '132', '133', '134', '135',
        '136', '137', '138', '139', '140', '141', '142', '143', '144',
        '145', '146', '147', '148', '149', '150', '151', '152', '153',
        '154', '155', '156', '157', '158', '159', '160', '161', '162',
        '163', '164', '165', '166', '167', '168', '169', '170', '171',
        '172', '173', '174', '175', '176', '177', '178', '179', '180',
        '181', '182', '183', '184', '185', '186', '187', '188', '189',
        '190', '191', '192', '193', '194', '195', '196', '197', '198',
        '199', '200', '201', '202', '203', '204', '205', '206', '207',
        '208', '209', '210', '211', '212', '213', '214', '215', '216',
        '217', '218', '219', '220', '221', '222', '223', '224', '225',
        '226', '227', '228', '229', '230', '231', '232', '233', '234',
        '235', '236', '237', '238', '239', '240', '241', '242', '243',
        '244', '245', '246', '247', '248', '249', '250', '251', '252',
        '253', '254', '255', '256', '257', '258', '259', '260', '261',
        '262', '263', '264', '265', '266', '267', '268', '269', '270',
        '271', '272', '273', '274', '275', '276', '277', '278', '279',
        '280', '281', '282', '283', '284', '285', '286', '287', '288',
        '289', '290', '291', '292', '293', '294', '295', '296', '297',
        '298', '계', '기타'], dtype=object))

In [ ]:
# 외래 진료비에 대한 건강보험 평균 본인부담률 계산
df_외래 = df[df['진료형태'] == '외래'].copy()
df_외래 = df_외래[~df_외래['연령'].isin(['계']) & ~df_외래['298 질병분류'].isin(['계', '기타'])]
df_외래

,연령,298 질병분류,22대 질병분류,진료형태,진료실인원수,입내원일수,요양급여일수,진료비,급여비,진료실인원수(급여),급여건수(급여),입내원일수(급여),요양일수(급여),총진료비(급여),기금부담금(급여)
2,0,001,1,외래,0.0,0.0,24.0,91.0,75,0,0,0,0,0,0
5,0,002,1,외래,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0
8,0,003,1,외래,1.0,1.0,1.0,21.0,19,0,0,0,0,0,0
11,0,004,1,외래,2.0,5.0,32.0,149.0,132,0,0,0,0,0,0
14,0,005,1,외래,39804.0,79130.0,387421.0,2789823.0,2487008,330,613,613,617,14929250,14735460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15281,75-,294,21,외래,0.0,0.0,163.0,458.0,321,0,0,0,0,0,0
15284,75-,295,21,외래,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0
15287,75-,296,21,외래,3.0,9.0,35.0,655.0,297,0,0,0,0,0,0
15290,75-,297,21,외래,471348.0,895890.0,1784028.0,106009702.0,81958576,45922,103314,93910,103539,10804104600,10357526350
15293,75-,298,21,외래,192222.0,573035.0,7707272.0,59332534.0,42851189,16537,49789,48744,81971,3083731320,3019396770

In [ ]:
df['22대 질병분류'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '21', '계', '기타'],
      dtype=object)

In [ ]:
a = df_외래['진료비'].sum()
a_임신출산 = df_외래[df_외래['22대 질병분류'] == "15"]['진료비'].sum()
b = df_외래['급여비'].sum()
b_임신출산 = df_외래[df_외래['22대 질병분류'] == "15"]['급여비'].sum()

value = (a-b)/a
formatted = f"{value * 100:.2f}%"

print("외래 급여에 대한 건강보험 평균 본인부담률:", formatted)

외래 급여에 대한 건강보험 평균 본인부담률: 28.50%

In [ ]:
v4세대_임신출산고려X = (a-b) * (1-0.2) * 1000
v4세대_임신출산고려 = ((a-a_임신출산)-(b-b_임신출산)) * (1-0.2) * 1000
v5세대 = (a-b) * (1-0.285) * 1000

print(f"4세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측 (임신출산 고려X): 약 {round(v4세대_임신출산고려X):,.0f}(원)")
print(f"4세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측: 약 {round(v4세대_임신출산고려):,.0f}(원)")
print(f"5세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측: 약 {round(v5세대):,.0f}(원)")

4세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측 (임신출산 고려X): 약 15,600,044,203,200(원)
4세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측: 약 15,581,519,274,400(원)
5세대 기준 2023년 급여 본인부담금에 대한 실손보험 보험금 지출 예측: 약 13,942,539,506,610(원)

In [ ]:
# cf. 입원 진료비에 대한 건강보험 평균 본인부담률 (20% 언저리여야함)
df_입원 = df[df['진료형태'] == '입원'].copy()
df_입원 = df_입원[~df_입원['연령'].isin(['계']) & ~df_입원['298 질병분류'].isin(['계', '기타'])]

a = df_입원['진료비'].sum()
b = df_입원['급여비'].sum()

value = (a-b)/a
formatted = f"{value * 100:.2f}%"

print("입원 급여에 대한 건강보험 평균 본인부담률:", formatted)

입원 급여에 대한 건강보험 평균 본인부담률: 18.86%